"""Shared WebSocket wire codec and encode/decode helpers.

Used by soothe-daemon (server channel) and soothe-client-python (transport).
Not a live WebSocket client — that lives in ``soothe_client``.
"""

from soothe_sdk.wire.codec import (
    DEFAULT_PROTO,
    BatchRequest,
    BatchRequestEnvelope,
    BatchResponseEnvelope,
    ConnectionAckEnvelope,
    ConnectionAckResult,
    ConnectionInitEnvelope,
    ConnectionInitParams,
    ErrorEnvelope,
    MessageType,
    PingEnvelope,
    PongEnvelope,
    ProtocolError,
    ResponseEnvelope,
    WireEnvelope,
    coerce_tool_call_chunk_args_for_wire,
    decode_envelope,
    deserialize_langchain_message_from_wire,
    encode_envelope,
    envelope_langchain_message_dict,
    flatten_enveloped_message_dict,
    messages_from_wire_dicts,
    prepare_stream_data_for_wire,
    prepare_stream_message_for_wire,
    serialize_langchain_message_for_wire,
)
from soothe_sdk.wire.protocol import (
    WorkspaceMapping,
    decode,
    decode_websocket_text,
    encode,
    encode_websocket_text,
    preview_first,
)

__all__ = [
    "DEFAULT_PROTO",
    "BatchRequest",
    "BatchRequestEnvelope",
    "BatchResponseEnvelope",
    "ConnectionAckEnvelope",
    "ConnectionAckResult",
    "ConnectionInitEnvelope",
    "ConnectionInitParams",
    "ErrorEnvelope",
    "MessageType",
    "PingEnvelope",
    "PongEnvelope",
    "ProtocolError",
    "ResponseEnvelope",
    "WireEnvelope",
    "WorkspaceMapping",
    "coerce_tool_call_chunk_args_for_wire",
    "decode_envelope",
    "deserialize_langchain_message_from_wire",
    "encode_envelope",
    "envelope_langchain_message_dict",
    "flatten_enveloped_message_dict",
    "messages_from_wire_dicts",
    "prepare_stream_data_for_wire",
    "prepare_stream_message_for_wire",
    "serialize_langchain_message_for_wire",
    "decode",
    "decode_websocket_text",
    "encode",
    "encode_websocket_text",
    "preview_first",
]
